### PR TITLE
Update PlayerMMovement.cs

### PR DESCRIPTION
**Pull request by TakumiPanda**
Added jumping mechanics. The player can now jump using the RMB (fire2) while moving or staying still. The player can only jump once, double jump or power jumping still being considered by the team.

### CODE REVIEW

**Comment by PizzaPartyInc** [comment]
Jumping works, the height and particulars can be addressed in a separate task.
The puzzle level would have to be adjusted to account for jumping in form of:
- Player can jump out of bounds.
   - Probably need to add some collidable borders just outside of the screen viewable area.
- Player can briefly stand on Leavers, but that counts as interacting and fading to the main screen, so acceptable for now. 
    - Maybe vertical collision borders for leavers should be adjusted.

The puzzle level adjustments can be done in context of additional trello card. Created one: https://trello.com/c/kbU7J1bu
Leaving it to @Endrophes to have a final say.

**Comment by TakumiPanda** [comment]
For the player can leave out of bounds, I thought we were going to have walls on the side that the player can run into. Else I can add code for an invisible wall but it'll have to use magic numbers which we are trying to avoid for coding standard and in general shouldn't use.
For the player standing on the leavers, I would need to see the leavers code and attributes so the player can pass through it but can still interact with them.

**Comment by Endrophes** [comment]
In this case, lets add the walls to the level as that is a faster change with out editing code.

**Comment by Endrophes** [comment]
I'm getting an error.

image


Also I'm clicking the right mouse button and the character is not jumping.

To Replicate:

1. Load SimpleScene
2. Play
3. press right mouse button

**Comment by PizzaPartyInc** [comment]
@Endrophes My test was done on the latest `main` branch state, where Player had RigidBody2D, it works there. Current branch state is a bit outdated.

**Comment by PizzaPartyInc** [comment]
Closing this PR as commit from it already got merged to `main` branch as part of another PR (got cherry-picked into it): https://github.com/conclusions-dissolutions/twisting-fate/pull/22

**Pull request closed without merging**
